[[gwas]]
name = "fast_ins_adj_bmi"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_fi.Chenji2021_Glycaemic_EU.FIadjBMI.txt"
[[gwas]]
name = "hdl"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_hdl.Graham_2021_lipids_EU.HDL.txt"
[[gwas]]
name = "hipc"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_hipc.GWAS_GIANT-A_eu.HIPC.txt"
[[gwas]]
name = "tg"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_tg.Graham_2021_lipids_EU.TG.txt"
[[gwas]]
name = "t2d"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_t2d.Mahajan2022_T2D_EU.txt"

[files]
trace = "/humgen/diabetes2/users/oliverr/mocasa/test/trace"
params = "/humgen/diabetes2/users/oliverr/mocasa/test/params"

[train]
ids_file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_lipo_var_ids/aligned_lipo_var_ids_LPLremoved.txt"
n_steps_burn_in = 10000
n_samples_per_iteration = 100
n_iterations_per_round = 1000
n_rounds = 10000

[classify]
n_steps_burn_in = 20000
n_samples = 200000
out_file = "/humgen/diabetes2/users/oliverr/mocasa/test/mus"
trace_ids = [
    "10_34224116_C_T", "11_116648917_C_G", "1_26277722_G_A", "1_86463640_G_A", "2_70269302_T_C", "8_19813529_A_G",
    "4_90694497_A_G", "9_89480473_G_A", "9_89482944_A_G", "9_89484280_A_G", "9_89485991_G_C", "9_89486666_T_C",
    "9_89490810_C_T"
]

