[[gwas]]
name = "fast_ins_adj_bmi"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_fi.Chenji2021_Glycaemic_EU.FIadjBMI.txt"
[[gwas]]
name = "hdl"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_hdl.Graham_2021_lipids_EU.HDL.txt"
[[gwas]]
name = "hipc"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_hipc.GWAS_GIANT-A_eu.HIPC.txt"
[[gwas]]
name = "tg"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_tg.Graham_2021_lipids_EU.TG.txt"
[[gwas]]
name = "t2d"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_adj/aligned_adj_t2d.Mahajan2022_T2D_EU.txt"

[train]
ids_file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned_lipo_var_ids/aligned_lipo_var_ids_LPLremoved.txt"
n_steps_burn_in = 1500000
n_steps_per_sample = 10
n_samples_per_iteration = 100
n_iterations_per_round = 15000
n_rounds = 100
