[[gwas]]
name = "fast_ins_adj_bmi"
file = "/home/oliverr/phenet/gwas/aligned_adj_fi.Chenji2021_Glycaemic_EU.FIadjBMI.txt"
[[gwas]]
name = "hdl"
file = "/home/oliverr/phenet/gwas/aligned_adj_hdl.Graham_2021_lipids_EU.HDL.txt"
[[gwas]]
name = "hipc"
file = "/home/oliverr/phenet/gwas/aligned_adj_hipc.GWAS_GIANT-A_eu.HIPC.txt"
[[gwas]]
name = "tg"
file = "/home/oliverr/phenet/gwas/aligned_adj_tg.Graham_2021_lipids_EU.TG.txt"
[[gwas]]
name = "t2d"
file = "/home/oliverr/phenet/gwas/aligned_adj_t2d.Mahajan2022_T2D_EU.txt"

[files]
trace = "/mnt/c/Users/oliverr/mocasa/test/trace"
params = "/mnt/c/Users/oliverr/mocasa/test/params"

[train]
ids_file = "/home/oliverr/phenet/training_var_list"
n_steps_burn_in = 20000
n_samples_per_iteration = 200
n_iterations_per_round = 1000
n_rounds = 10000

[classify]
params_override = { mu = 0.0, tau = 100 }
n_steps_burn_in = 10000
n_samples = 100000
out_file = "/mnt/c/Users/oliverr/mocasa/test/mus"
trace_ids = [
    "11_59460872_A_G", "12_41748768_T_C", "12_97340198_T_C", "19_49657334_A_G", "20_47234885_C_T", "2_70269302_T_C",
    "4_90694497_A_G", "5_161116559_T_C", "6_77127735_G_A", "8_113737999_G_C"
]


