[files]
params = "phenet/ex2/mocasa_params"

[[gwas]]
name = "fast_ins_adj_bmi"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned/aligned_fi.Chenji2021_Glycaemic_EU.FIadjBMI.txt"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "hdl"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned/aligned_hdl.Graham_2021_lipids_EU.HDL.txt"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "hipc"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned/aligned_hipc.GWAS_GIANT-A_eu.HIPC.txt"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "tg"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned/aligned_tg.Graham_2021_lipids_EU.TG.txt"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "t2d"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/02.curate/output/aligned/aligned_t2d.Mahajan2022_T2D_EU.txt"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[train]
ids_file = ""
n_steps_burn_in = 10000
n_samples_per_iteration = 100
n_iterations_per_round = 1000
n_rounds = 10000

[classify]
n_steps_burn_in = 10000
n_samples = 100000
out_file = "phenet/ex2/mocasa_out"
