[files]
params = "phenet/mocasa_params.json"

[[gwas]]
name = "di"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_di.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "cir"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_cir.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "alp"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_alp.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "fg"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_fg.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "pltvol"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_pltvol.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[[gwas]]
name = "t2d"
file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters/combine/aligned_t2d.tsv"

[gwas.cols]
id = "VAR_ID"
effect = "BETA"
se = "SE"

[train]
ids_file = "/humgen/diabetes2/users/satoshi/03.variant_based/03.input_gwas/07.udler2023_comp_clusters_20sd/aligned_hyperinsulin/varId_aligned_hyperinsulin_nooutlier.txt"
n_steps_burn_in = 10000
n_samples_per_iteration = 100
n_iterations_per_round = 1000
n_rounds = 10000

[classify]
n_steps_burn_in = 10000
n_samples = 100000
out_file = "phenet/classify_out"
